// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:

import 'firebase_options.dart';


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtq5G86zQUYE-yuS9DxdHp8kMZOaR-SF4',
    appId: '1:659081979812:web:6b8b1cc7666b26230fc331',
    messagingSenderId: '659081979812',
    projectId: 'chat-app-9b76b',
    authDomain: 'chat-app-9b76b.firebaseapp.com',
    storageBucket: 'chat-app-9b76b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7xbGFmHOhm7cJvzw2yAgYpmVAjG8MCoU',
    appId: '1:659081979812:android:6188d9969976c35b0fc331',
    messagingSenderId: '659081979812',
    projectId: 'chat-app-9b76b',
    storageBucket: 'chat-app-9b76b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYa4nAhd9QAwE85IhA_yQ6qflzGRB_6Gw',
    appId: '1:659081979812:ios:cd4844faafe5208b0fc331',
    messagingSenderId: '659081979812',
    projectId: 'chat-app-9b76b',
    storageBucket: 'chat-app-9b76b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYa4nAhd9QAwE85IhA_yQ6qflzGRB_6Gw',
    appId: '1:659081979812:ios:cd4844faafe5208b0fc331',
    messagingSenderId: '659081979812',
    projectId: 'chat-app-9b76b',
    storageBucket: 'chat-app-9b76b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtq5G86zQUYE-yuS9DxdHp8kMZOaR-SF4',
    appId: '1:659081979812:web:92a226f1c52ffcae0fc331',
    messagingSenderId: '659081979812',
    projectId: 'chat-app-9b76b',
    authDomain: 'chat-app-9b76b.firebaseapp.com',
    storageBucket: 'chat-app-9b76b.appspot.com',
  );
}
